service: alfred

plugins:
  - serverless-python-requirements
  - serverless-offline

package:
  individually: true
  exclude:
    - __pycache__
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

provider:
  name: aws
  runtime: python3.6
  profile: default
  region: eu-west-1
  versionFunctions: false
  stage: dev
  environment:
    S3_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-data
    MAILER_URL: 'https://us-central1-mailer-69581.cloudfunctions.net/mail/'
    YTS_URL: 'https://yts.am'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*'


functions:
  - ${file(functions/yts/index.yml)}

resources:
  Resources:
    S3TranscriptionBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}